### ISSUE TITLE
Investigate connect_hub performance when used against large, S3-based hubs

### ISSUE THREAD

**Issue by bsweger** [hubverse-org/hubData#37]
**Background**

We've previously identified non-uniform parquet schemas as a performance culprit when using `hubData` (because you have to do a `collect()` before you can filter). That issue is logged here: https://github.com/Infectious-Disease-Modeling-Hubs/hubverse-transform/issues/14

However, now that we have a larger hub on S3 (bucket: `temp-flusight-archive-hub`), we've found that even creating the initial `connect_hub` function (prior to doing any manipulations or collects) takes a prohibitively long time. @nickreich [reported ~20 minutes](https://reichlab.slack.com/archives/C07429CG171/p1718115477925559?thread_ts=1718043818.693069&cid=C07429CG171), and I was getting ~8 min.

@annakrystalli previously [ran some thorough benchmarks](https://partition-benchmarking.netlify.app/) against a copy of the 2023-24 CDC FluSight hub, which had a baseline of 613 .csv model-output files at the time. This analysis found significant performance gains by converting the files to parquet and keeping them in the same place (i.e, same folder name, same filename).

The flusight archives have 4,217 parquet files in the `model-output` folder. 

**Definition of done**

- [x] Determine cause(s) of the poor `connect_hub` performance against a large set of model-output files on S3
- [x] Make recommendations for next steps and open any corresponding issues

**Comment by bsweger** [comment]
Based on the above, I'd recommend looking for an alternate way or place for doing the non-performant data quality checks in `hub_connect` (_i.e._, the first item in the above comment).

Partitioning the data is almost certainly something we should do. Not only to speed up `hub_connect` but also to ensure more performant data access for downstream applications like dashboards and visualizations.

However, implementing partitioning involves more work with more moving pieces. For example:

- `hub_connect` doesn't work "out of the box" with alternate partitions (or maybe I missed something, entirely possible!)
- would anything downstream break if we publish model-output files that aren't named in the `round_id-model_id` format?
- for active hubs, we'd need a way to ensure periodic compaction of the model-output files in S3 (so we don't get the "many small files" over time)

**Comment by annakrystalli** [comment]
Note that excluding invalid files is needed if any other file type exists in the directory other than the file type being opened e.g. mixed file types or READMES etc. As these are common in standard hubs, the default is to remove them on opening, otherwise `open_dataset` just fails.

If the cloud transformation can guarantee these conditions, we can surface arguments to turn those checks off (probably a good idea to surface them anyways). 

It would be nicer however for the function to be able to detect that it's dealing with a cloud hub were the above conditions are guaranteed and set those checks to off by default in that case. Perhaps through including a `.cloud-hub` file in the root of the hub that the function could use to detect such a hub?

Re: the repartioning, this will be easy to adapt `hubData` to handle but more work to do the actual repartioning.

Also it might be useful to compare to how easy it would be to just add files to a duckdb database instead of repartitioning.

**Comment by bsweger** [comment]
Thanks for the 👀 @annakrystalli! Am splitting the response into 2 comments, one for validation defaults and one for duckdb.

> Note that excluding invalid files is needed if any other file type exists in the directory other than the file type being opened e.g. mixed file types or READMES etc. As these are common in standard hubs, the default is to remove them on opening, otherwise `open_dataset` just fails.
> 
> If the cloud transformation can guarantee these conditions, we can surface arguments to turn those checks off (probably a good idea to surface them anyways).
> 
> It would be nicer however for the function to be able to detect that it's dealing with a cloud hub were the above conditions are guaranteed and set those checks to off by default in that case. Perhaps through including a `.cloud-hub` file in the root of the hub that the function could use to detect such a hub?
> 

Good call--love the idea of implementing sensible default behaviors on users' behalf depending on where the data is. Currently, the [transform function won't transform anything other than a .csv or .parquet file.](https://github.com/Infectious-Disease-Modeling-Hubs/hubverse-transform/blob/main/src/hubverse_transform/model_output.py#L41). So I believe we can safely default to skipping checks for cloud-based hubs.

Rather than adding an explicit `.cloud-hub` file to hub repos, could we programmatically determine the default behavior? For example, looking at the attributes of Arrow's SubTreeFileSystem when in `connect_hub.SubTreeFileSystem` (_e.g._, `if hub_path[["url_scheme"]] == "s3"`)? Or even just set the default to skip checks anytime the `UseMethod` dispatches to `connect_hub.SubTreeFileSystem`?

(While still surfacing the option to run or skip so people can override)

**Comment by bsweger** [comment]
> 
> Re: the repartioning, this will be easy to adapt `hubData` to handle but more work to do the actual repartioning.
> 
> Also it might be useful to compare to how easy it would be to just add files to a duckdb database instead of repartitioning.



> > Rather than adding an explicit .cloud-hub file to hub repos, could we programmatically determine the default behavior? For example, looking at the attributes of Arrow's SubTreeFileSystem when in connect_hub.SubTreeFileSystem (e.g., if hub_path[["url_scheme"]] == "s3")? Or even just set the default to skip checks anytime the UseMethod dispatches to connect_hub.SubTreeFileSystem?
> 
> I initially considered that but the files just being on s3 does not guarantee that someone has for example not just dumped a hub as is on s3 or mirrored it in some other way (not out transformation action). What I was trying to get to with the file is some sort of signature that a cloud hub has been generated by our transformation function and therefore guaranteed to work without the checks. Very open to other suggestions!

That's true, but as long as we're planning to allow someone to override the default and require checks/exclusions if required, I'd vote for "few moving parts" and check programmatically.

**Comment by bsweger** [comment]
> Re: the repartioning, this will be easy to adapt `hubData` to handle but more work to do the actual repartioning.

Oh that's great! Re: actual repartioning, I was thinking that the transform function could write out the data according to the partioning strategy we decide on. The bigger challenge, I think, is merging/compacting the small parquet files that will accumulate over time (again, because model-output files are being written to S3 one at a time).

Sounds like you were thinking something else, so maybe worth a chat next week?
 
> Also it might be useful to compare to how easy it would be to just add files to a duckdb database instead of repartitioning.

Ah, I didn't have much luck with DuckDB for this purpose and should have noted that ([updated](https://reichlab.atlassian.net/wiki/spaces/~7120203df9acbaa41944839969b0fa9d27fea5/pages/35913736/S3+Data+Access+Notes)).. I did think about a persistent DuckDB file on S3, but there are a few challenges:

- Persistent DuckDB database files on S3 are read-only--you can't update them
- I got intermittent errors when reading large amounts of data using the R DuckDB client
- (caveat, this is based on limited testing on a laptop with a lot of memory): I had better performance using DuckDB's `read_parquet` function to create an in-memory table of model-output data than using the data file hosted on S3

Relying on clients like Arrow and DuckDB that can spin through a directory of parquet files (vs using a database) has the advantage of returning information about submissions as they arrive, even if we'd need to do a scheduled compaction.

Arrow works pretty well for multi-parquet file reads, especially when you're filtering on the partition columns. Since hubData is already based on Arrow and you've already smoothed out so many of the edge cases, we could stick with it for reading data, and try it out for partitioning data if we decide to do that.

**Comment by nickreich** [comment]
One question I have about a potential future partitioning strategy standard, is that the one employed above `target/output_type/location` is specific to task-id fields that are project-specific. As in, `output_type` is a standard field, but both `target` and `location` might not be present for a hub. Would the partition need to be specified somewhere by the hub prior to creating the s3 bucket, and then the transform code would programmatically adapt?

**Comment by annakrystalli** [comment]
I feel partitioning should not be enforced by us but configurable by hub Admins. We can of course recommend sensible defaults in `hubTemplate` (or wherever we host examples of configuring a hub for cloud).

**Comment by bsweger** [comment]
I opened an issue to allow skipping data checks in `connect_hub` and `connect_model_output`:  https://github.com/hubverse-org/hubData/issues/43

As for the second question of data partitioning, agree with all of the above that there are additional considerations. And after a recent discussion, I've been thinking more about DuckDB...

DuckDB files hosted on S3 are read-only, which I'd originally considered a deal-breaker. However, based on a recent conversation, I think it's worth another look for these reasons:

- our current dashboard priorities (viz, scoring) do not require real-time data updates: their backend data needs to be updated only after each round closes
- if we consider scoring (which wasn't part of our retreat conversation), we'd ideally want a place to store model scores after computing them, so we don't have to run computations on the fly...once we enter the territory of computing and storing additional model/round-related information, a database option becomes more attractive

If there's a world where we can get reasonable DuckDB performance and can work out a way to recreate it and update the S3 .db file as part of a "round closing" process, it might be worth considering as a stand-alone data access solution or as part of data partitioning/compaction strategy.
